PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX heat: <https://w3id.org/heat#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT ?t ?label
WHERE {
    ?t a heat:Tool ;
    rdfs:label ?label .
}