#+ endpoint: https://knowledge.c-innovationhub.com/heat
#+ endpoint-method: GET
#+ summary: Get the questions associated to a construct
#+ tags:
#+ - Constructs

PREFIX heat: <https://w3id.org/heat#>
PREFIX dct:	<http://purl.org/dc/terms/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sur: <https://w3id.org/survey-ontology#>

SELECT DISTINCT ?questionText ?questionOptionsText ?questionOptionsValues ?questionReversed
WHERE {
	?_construct_iri a heat:Construct ;
		heat:hasQuestion ?constructQuestion .
	?constructQuestion a sur:Question ;
		sur:questionText ?questionText ;
		heat:hasLikertAnswer [
			heat:textualValueRange ?questionOptionsText ;
			heat:numericalValueRange ?questionOptionsValues ;
			heat:isScaleReversed ?questionReversed ;
		] .
}